# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/master.xdc

# Block Designs: bd/mitx_petalinux/mitx_petalinux.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux || ORIG_REF_NAME==mitx_petalinux}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_processing_system7_0_0/mitx_petalinux_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_processing_system7_0_0 || ORIG_REF_NAME==mitx_petalinux_processing_system7_0_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_processing_system7_0_axi_periph_0/mitx_petalinux_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==mitx_petalinux_processing_system7_0_axi_periph_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_2_1/mitx_petalinux_axi_gpio_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_2_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_2_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_1_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_1_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_0_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_0_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_xbar_0/mitx_petalinux_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_xbar_0 || ORIG_REF_NAME==mitx_petalinux_xbar_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_clk_wiz_0_1/mitx_petalinux_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_clk_wiz_0_1 || ORIG_REF_NAME==mitx_petalinux_clk_wiz_0_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_0/mitx_petalinux_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_0 || ORIG_REF_NAME==mitx_petalinux_auto_pc_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_1/mitx_petalinux_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_1 || ORIG_REF_NAME==mitx_petalinux_auto_pc_1}]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_processing_system7_0_0/mitx_petalinux_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_processing_system7_0_0 || ORIG_REF_NAME==mitx_petalinux_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_2_1/mitx_petalinux_axi_gpio_2_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_2_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_2_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_2_1/mitx_petalinux_axi_gpio_2_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_2_1/mitx_petalinux_axi_gpio_2_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_2_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_2_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_1_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_1_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_0_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_0_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_xbar_0/mitx_petalinux_xbar_0_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_clk_wiz_0_1/mitx_petalinux_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_clk_wiz_0_1 || ORIG_REF_NAME==mitx_petalinux_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_clk_wiz_0_1/mitx_petalinux_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_clk_wiz_0_1 || ORIG_REF_NAME==mitx_petalinux_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_clk_wiz_0_1/mitx_petalinux_clk_wiz_0_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_0/mitx_petalinux_auto_pc_0_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_1/mitx_petalinux_auto_pc_1_ooc.xdc

# XDC: bd/mitx_petalinux/mitx_petalinux_ooc.xdc
