# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z100ffg900-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.cache/wt [current_project]
set_property parent.project_path /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/mitx_petalinux.bd
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_processing_system7_0_0/mitx_petalinux_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_2_1/mitx_petalinux_axi_gpio_2_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_2_1/mitx_petalinux_axi_gpio_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_2_1/mitx_petalinux_axi_gpio_2_1.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_xbar_0/mitx_petalinux_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_0/mitx_petalinux_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_1/mitx_petalinux_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/mitx_petalinux_ooc.xdc]
set_property is_locked true [get_files /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/mitx_petalinux.bd]

read_verilog -library xil_defaultlib /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/sources_1/bd/mitx_petalinux/hdl/mitx_petalinux_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files /home/hildeb47/proj/ECE1373_ghostSynth/MITXZ7100/mitx_petalinux.srcs/constrs_1/new/master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mitx_petalinux_wrapper -part xc7z100ffg900-1


write_checkpoint -force -noxdef mitx_petalinux_wrapper.dcp

catch { report_utilization -file mitx_petalinux_wrapper_utilization_synth.rpt -pb mitx_petalinux_wrapper_utilization_synth.pb }
