// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Echo,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z100ffg900-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=12,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=5,HLS_SYN_FF=1131,HLS_SYN_LUT=1251}" *)

module Echo (
        ap_clk,
        ap_rst_n,
        value_in_V_TDATA,
        value_in_V_TVALID,
        value_in_V_TREADY,
        value_out_V_TDATA,
        value_out_V_TVALID,
        value_out_V_TREADY,
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;
parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] value_in_V_TDATA;
input   value_in_V_TVALID;
output   value_in_V_TREADY;
output  [31:0] value_out_V_TDATA;
output   value_out_V_TVALID;
input   value_out_V_TREADY;
input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;

reg    ap_rst_n_inv;
reg   [31:0] value_in_V_0_data_out;
wire    value_in_V_0_vld_in;
wire    value_in_V_0_vld_out;
wire    value_in_V_0_ack_in;
reg    value_in_V_0_ack_out;
reg   [31:0] value_in_V_0_payload_A;
reg   [31:0] value_in_V_0_payload_B;
reg    value_in_V_0_sel_rd;
reg    value_in_V_0_sel_wr;
wire    value_in_V_0_sel;
wire    value_in_V_0_load_A;
wire    value_in_V_0_load_B;
reg   [1:0] value_in_V_0_state;
wire    value_in_V_0_state_cmp_full;
reg   [31:0] value_out_V_1_data_out;
reg    value_out_V_1_vld_in;
wire    value_out_V_1_vld_out;
wire    value_out_V_1_ack_in;
wire    value_out_V_1_ack_out;
reg   [31:0] value_out_V_1_payload_A;
reg   [31:0] value_out_V_1_payload_B;
reg    value_out_V_1_sel_rd;
reg    value_out_V_1_sel_wr;
wire    value_out_V_1_sel;
wire    value_out_V_1_load_A;
wire    value_out_V_1_load_B;
reg   [1:0] value_out_V_1_state;
wire    value_out_V_1_state_cmp_full;
wire   [31:0] delay;
wire   [31:0] scale;
reg   [0:0] guard_variable_for_E;
reg   [31:0] readBuffer;
reg   [12:0] buffer_r_address0;
reg    buffer_r_ce0;
reg    buffer_r_we0;
wire   [31:0] buffer_r_q0;
reg   [31:0] writeBuffer;
reg    value_in_V_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state8;
reg    value_out_V_TDATA_blk_n;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg   [31:0] scale_read_reg_210;
wire    ap_CS_fsm_state1;
wire   [31:0] tmp_2_i_fu_132_p2;
wire   [0:0] guard_variable_for_E_load_fu_124_p1;
wire    ap_CS_fsm_state2;
reg   [31:0] buffer_load_reg_233;
wire    ap_CS_fsm_state3;
wire   [31:0] grp_fu_120_p2;
reg   [31:0] tmp_5_reg_238;
wire    ap_CS_fsm_state7;
wire   [31:0] grp_fu_114_p2;
reg   [31:0] current_value_reg_248;
reg   [31:0] readBuffer_loc_reg_105;
wire  signed [63:0] tmp_4_fu_144_p1;
wire  signed [63:0] tmp_6_fu_179_p1;
wire   [31:0] storemerge_fu_161_p3;
wire   [31:0] storemerge5_fu_196_p3;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_9_fu_149_p2;
wire   [31:0] tmp_s_fu_155_p2;
wire   [0:0] tmp_8_fu_184_p2;
wire   [31:0] tmp_7_fu_190_p2;
reg    grp_fu_114_ce;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg   [12:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 value_in_V_0_sel_rd = 1'b0;
#0 value_in_V_0_sel_wr = 1'b0;
#0 value_in_V_0_state = 2'd0;
#0 value_out_V_1_sel_rd = 1'b0;
#0 value_out_V_1_sel_wr = 1'b0;
#0 value_out_V_1_state = 2'd0;
#0 guard_variable_for_E = 1'd0;
#0 readBuffer = 32'd0;
#0 writeBuffer = 32'd0;
#0 ap_CS_fsm = 13'd1;
end

Echo_buffer_r #(
    .DataWidth( 32 ),
    .AddressRange( 4800 ),
    .AddressWidth( 13 ))
buffer_r_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_r_address0),
    .ce0(buffer_r_ce0),
    .we0(buffer_r_we0),
    .d0(current_value_reg_248),
    .q0(buffer_r_q0)
);

Echo_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
Echo_CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .delay(delay),
    .scale(scale)
);

Echo_fadd_32ns_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Echo_fadd_32ns_32bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(value_in_V_0_data_out),
    .din1(tmp_5_reg_238),
    .ce(grp_fu_114_ce),
    .dout(grp_fu_114_p2)
);

Echo_fmul_32ns_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Echo_fmul_32ns_32cud_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(buffer_load_reg_233),
    .din1(scale_read_reg_210),
    .ce(1'b1),
    .dout(grp_fu_120_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        value_in_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == value_in_V_0_ack_out) & (1'b1 == value_in_V_0_vld_out))) begin
            value_in_V_0_sel_rd <= ~value_in_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        value_in_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == value_in_V_0_vld_in) & (1'b1 == value_in_V_0_ack_in))) begin
            value_in_V_0_sel_wr <= ~value_in_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        value_in_V_0_state <= 2'd0;
    end else begin
        if ((((1'b0 == value_in_V_0_vld_in) & (1'b1 == value_in_V_0_ack_out) & (value_in_V_0_state == 2'd3)) | ((1'b0 == value_in_V_0_vld_in) & (value_in_V_0_state == 2'd2)))) begin
            value_in_V_0_state <= 2'd2;
        end else if ((((1'b1 == value_in_V_0_vld_in) & (1'b0 == value_in_V_0_ack_out) & (value_in_V_0_state == 2'd3)) | ((1'b0 == value_in_V_0_ack_out) & (value_in_V_0_state == 2'd1)))) begin
            value_in_V_0_state <= 2'd1;
        end else if ((((1'b1 == value_in_V_0_vld_in) & (value_in_V_0_state == 2'd2)) | ((1'b1 == value_in_V_0_ack_out) & (value_in_V_0_state == 2'd1)) | ((value_in_V_0_state == 2'd3) & ~((1'b1 == value_in_V_0_vld_in) & (1'b0 == value_in_V_0_ack_out)) & ~((1'b0 == value_in_V_0_vld_in) & (1'b1 == value_in_V_0_ack_out))))) begin
            value_in_V_0_state <= 2'd3;
        end else begin
            value_in_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        value_out_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == value_out_V_1_ack_out) & (1'b1 == value_out_V_1_vld_out))) begin
            value_out_V_1_sel_rd <= ~value_out_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        value_out_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == value_out_V_1_vld_in) & (1'b1 == value_out_V_1_ack_in))) begin
            value_out_V_1_sel_wr <= ~value_out_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        value_out_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == value_out_V_1_vld_in) & (1'b1 == value_out_V_1_ack_out) & (2'd3 == value_out_V_1_state)) | ((1'b0 == value_out_V_1_vld_in) & (2'd2 == value_out_V_1_state)))) begin
            value_out_V_1_state <= 2'd2;
        end else if ((((1'b1 == value_out_V_1_vld_in) & (1'b0 == value_out_V_1_ack_out) & (2'd3 == value_out_V_1_state)) | ((1'b0 == value_out_V_1_ack_out) & (2'd1 == value_out_V_1_state)))) begin
            value_out_V_1_state <= 2'd1;
        end else if ((((1'b1 == value_out_V_1_vld_in) & (2'd2 == value_out_V_1_state)) | ((1'b1 == value_out_V_1_ack_out) & (2'd1 == value_out_V_1_state)) | ((2'd3 == value_out_V_1_state) & ~((1'b1 == value_out_V_1_vld_in) & (1'b0 == value_out_V_1_ack_out)) & ~((1'b0 == value_out_V_1_vld_in) & (1'b1 == value_out_V_1_ack_out))))) begin
            value_out_V_1_state <= 2'd3;
        end else begin
            value_out_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd1 == guard_variable_for_E_load_fu_124_p1)) begin
            readBuffer_loc_reg_105 <= readBuffer;
        end else if ((1'd0 == guard_variable_for_E_load_fu_124_p1)) begin
            readBuffer_loc_reg_105 <= tmp_2_i_fu_132_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_load_reg_233 <= buffer_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (value_out_V_1_ack_in == 1'b1))) begin
        current_value_reg_248 <= grp_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'd0 == guard_variable_for_E_load_fu_124_p1))) begin
        guard_variable_for_E <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        readBuffer <= storemerge_fu_161_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        scale_read_reg_210 <= scale;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_5_reg_238 <= grp_fu_120_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == value_in_V_0_load_A)) begin
        value_in_V_0_payload_A <= value_in_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == value_in_V_0_load_B)) begin
        value_in_V_0_payload_B <= value_in_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == value_out_V_1_load_A)) begin
        value_out_V_1_payload_A <= grp_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == value_out_V_1_load_B)) begin
        value_out_V_1_payload_B <= grp_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (value_out_V_1_ack_in == 1'b1))) begin
        writeBuffer <= storemerge5_fu_196_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        buffer_r_address0 = tmp_6_fu_179_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buffer_r_address0 = tmp_4_fu_144_p1;
    end else begin
        buffer_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state13) & (value_out_V_1_ack_in == 1'b1)))) begin
        buffer_r_ce0 = 1'b1;
    end else begin
        buffer_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (value_out_V_1_ack_in == 1'b1))) begin
        buffer_r_we0 = 1'b1;
    end else begin
        buffer_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state8) & (value_in_V_0_vld_out == 1'b1)) | ((1'b1 == ap_CS_fsm_state12) & (value_out_V_1_ack_in == 1'b1)) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        grp_fu_114_ce = 1'b1;
    end else begin
        grp_fu_114_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (value_in_V_0_vld_out == 1'b1))) begin
        value_in_V_0_ack_out = 1'b1;
    end else begin
        value_in_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == value_in_V_0_sel)) begin
        value_in_V_0_data_out = value_in_V_0_payload_B;
    end else begin
        value_in_V_0_data_out = value_in_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        value_in_V_TDATA_blk_n = value_in_V_0_state[1'd0];
    end else begin
        value_in_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == value_out_V_1_sel)) begin
        value_out_V_1_data_out = value_out_V_1_payload_B;
    end else begin
        value_out_V_1_data_out = value_out_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (value_out_V_1_ack_in == 1'b1))) begin
        value_out_V_1_vld_in = 1'b1;
    end else begin
        value_out_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state13))) begin
        value_out_V_TDATA_blk_n = value_out_V_1_state[1'd1];
    end else begin
        value_out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (value_in_V_0_vld_out == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (value_out_V_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (value_out_V_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign guard_variable_for_E_load_fu_124_p1 = guard_variable_for_E;

assign storemerge5_fu_196_p3 = ((tmp_8_fu_184_p2[0:0] === 1'b1) ? tmp_7_fu_190_p2 : 32'd0);

assign storemerge_fu_161_p3 = ((tmp_9_fu_149_p2[0:0] === 1'b1) ? tmp_s_fu_155_p2 : 32'd0);

assign tmp_2_i_fu_132_p2 = (32'd4800 - delay);

assign tmp_4_fu_144_p1 = $signed(readBuffer_loc_reg_105);

assign tmp_6_fu_179_p1 = $signed(writeBuffer);

assign tmp_7_fu_190_p2 = (writeBuffer + 32'd1);

assign tmp_8_fu_184_p2 = (($signed(writeBuffer) < $signed(32'd4800)) ? 1'b1 : 1'b0);

assign tmp_9_fu_149_p2 = (($signed(readBuffer_loc_reg_105) < $signed(32'd4800)) ? 1'b1 : 1'b0);

assign tmp_s_fu_155_p2 = (readBuffer_loc_reg_105 + 32'd1);

assign value_in_V_0_ack_in = value_in_V_0_state[1'd1];

assign value_in_V_0_load_A = (value_in_V_0_state_cmp_full & ~value_in_V_0_sel_wr);

assign value_in_V_0_load_B = (value_in_V_0_sel_wr & value_in_V_0_state_cmp_full);

assign value_in_V_0_sel = value_in_V_0_sel_rd;

assign value_in_V_0_state_cmp_full = ((value_in_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign value_in_V_0_vld_in = value_in_V_TVALID;

assign value_in_V_0_vld_out = value_in_V_0_state[1'd0];

assign value_in_V_TREADY = value_in_V_0_state[1'd1];

assign value_out_V_1_ack_in = value_out_V_1_state[1'd1];

assign value_out_V_1_ack_out = value_out_V_TREADY;

assign value_out_V_1_load_A = (value_out_V_1_state_cmp_full & ~value_out_V_1_sel_wr);

assign value_out_V_1_load_B = (value_out_V_1_sel_wr & value_out_V_1_state_cmp_full);

assign value_out_V_1_sel = value_out_V_1_sel_rd;

assign value_out_V_1_state_cmp_full = ((value_out_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign value_out_V_1_vld_out = value_out_V_1_state[1'd0];

assign value_out_V_TDATA = value_out_V_1_data_out;

assign value_out_V_TVALID = value_out_V_1_state[1'd0];

endmodule //Echo
