# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/master.xdc

# Block Designs: bd/mitx_petalinux/mitx_petalinux.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux || ORIG_REF_NAME==mitx_petalinux}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_processing_system7_0_0/mitx_petalinux_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_processing_system7_0_0 || ORIG_REF_NAME==mitx_petalinux_processing_system7_0_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_processing_system7_0_axi_periph_0/mitx_petalinux_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==mitx_petalinux_processing_system7_0_axi_periph_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_1_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_1_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_0_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_0_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_clk_wiz_0_1/mitx_petalinux_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_clk_wiz_0_1 || ORIG_REF_NAME==mitx_petalinux_clk_wiz_0_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_i2s_tx_fifo_0/mitx_petalinux_i2s_tx_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_i2s_tx_fifo_0 || ORIG_REF_NAME==mitx_petalinux_i2s_tx_fifo_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_i2s_tx_0/mitx_petalinux_i2s_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_i2s_tx_0 || ORIG_REF_NAME==mitx_petalinux_i2s_tx_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_atg_module_0_0/mitx_petalinux_atg_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_atg_module_0_0 || ORIG_REF_NAME==mitx_petalinux_atg_module_0_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_converter_0_0/mitx_petalinux_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_converter_0_0 || ORIG_REF_NAME==mitx_petalinux_converter_0_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_axi_interconnect_0_1/mitx_petalinux_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_interconnect_0_1 || ORIG_REF_NAME==mitx_petalinux_axi_interconnect_0_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_saw_1_0/mitx_petalinux_saw_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_saw_1_0 || ORIG_REF_NAME==mitx_petalinux_saw_1_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_saw_2_0/mitx_petalinux_saw_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_saw_2_0 || ORIG_REF_NAME==mitx_petalinux_saw_2_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_saw_3_0/mitx_petalinux_saw_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_saw_3_0 || ORIG_REF_NAME==mitx_petalinux_saw_3_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_mixer_0_0/mitx_petalinux_mixer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_mixer_0_0 || ORIG_REF_NAME==mitx_petalinux_mixer_0_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_latcherfloat_0_1/mitx_petalinux_latcherfloat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_latcherfloat_0_1 || ORIG_REF_NAME==mitx_petalinux_latcherfloat_0_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_saw_4_0/mitx_petalinux_saw_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_saw_4_0 || ORIG_REF_NAME==mitx_petalinux_saw_4_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_latcherfloat_1_0/mitx_petalinux_latcherfloat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_latcherfloat_1_0 || ORIG_REF_NAME==mitx_petalinux_latcherfloat_1_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_xlconstant_0_0/mitx_petalinux_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_xlconstant_0_0 || ORIG_REF_NAME==mitx_petalinux_xlconstant_0_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_FM_Synth_0_0/mitx_petalinux_FM_Synth_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_FM_Synth_0_0 || ORIG_REF_NAME==mitx_petalinux_FM_Synth_0_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_xbar_0/mitx_petalinux_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_xbar_0 || ORIG_REF_NAME==mitx_petalinux_xbar_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_xbar_1/mitx_petalinux_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_xbar_1 || ORIG_REF_NAME==mitx_petalinux_xbar_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_axis_interconnect_0_0/mitx_petalinux_axis_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_axis_interconnect_0_0 || ORIG_REF_NAME==mitx_petalinux_axis_interconnect_0_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_xbar_2/mitx_petalinux_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_xbar_2 || ORIG_REF_NAME==mitx_petalinux_xbar_2}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_9/mitx_petalinux_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_9 || ORIG_REF_NAME==mitx_petalinux_auto_pc_9}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_8/mitx_petalinux_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_8 || ORIG_REF_NAME==mitx_petalinux_auto_pc_8}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_7/mitx_petalinux_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_7 || ORIG_REF_NAME==mitx_petalinux_auto_pc_7}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_11/mitx_petalinux_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_11 || ORIG_REF_NAME==mitx_petalinux_auto_pc_11}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_10/mitx_petalinux_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_10 || ORIG_REF_NAME==mitx_petalinux_auto_pc_10}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_ss_slidr_0/mitx_petalinux_auto_ss_slidr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_ss_slidr_0 || ORIG_REF_NAME==mitx_petalinux_auto_ss_slidr_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_ss_slid_1/mitx_petalinux_auto_ss_slid_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_ss_slid_1 || ORIG_REF_NAME==mitx_petalinux_auto_ss_slid_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_ss_slid_0/mitx_petalinux_auto_ss_slid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_ss_slid_0 || ORIG_REF_NAME==mitx_petalinux_auto_ss_slid_0}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_6/mitx_petalinux_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_6 || ORIG_REF_NAME==mitx_petalinux_auto_pc_6}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_5/mitx_petalinux_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_5 || ORIG_REF_NAME==mitx_petalinux_auto_pc_5}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_4/mitx_petalinux_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_4 || ORIG_REF_NAME==mitx_petalinux_auto_pc_4}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_3/mitx_petalinux_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_3 || ORIG_REF_NAME==mitx_petalinux_auto_pc_3}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_2/mitx_petalinux_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_2 || ORIG_REF_NAME==mitx_petalinux_auto_pc_2}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_1/mitx_petalinux_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_1 || ORIG_REF_NAME==mitx_petalinux_auto_pc_1}]

# IP: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_0/mitx_petalinux_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mitx_petalinux_auto_pc_0 || ORIG_REF_NAME==mitx_petalinux_auto_pc_0}]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_processing_system7_0_0/mitx_petalinux_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_processing_system7_0_0 || ORIG_REF_NAME==mitx_petalinux_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==mitx_petalinux_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_rst_processing_system7_0_50M_0/mitx_petalinux_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_1_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_1_1/mitx_petalinux_axi_gpio_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_1_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_0_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_axi_gpio_0_1/mitx_petalinux_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_axi_gpio_0_1 || ORIG_REF_NAME==mitx_petalinux_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_clk_wiz_0_1/mitx_petalinux_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_clk_wiz_0_1 || ORIG_REF_NAME==mitx_petalinux_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_clk_wiz_0_1/mitx_petalinux_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_clk_wiz_0_1 || ORIG_REF_NAME==mitx_petalinux_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_clk_wiz_0_1/mitx_petalinux_clk_wiz_0_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_i2s_tx_fifo_0/mitx_petalinux_i2s_tx_fifo_0_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_i2s_tx_fifo_0/mitx_petalinux_i2s_tx_fifo_0/mitx_petalinux_i2s_tx_fifo_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_i2s_tx_fifo_0 || ORIG_REF_NAME==mitx_petalinux_i2s_tx_fifo_0}] {/inst }]/inst ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_i2s_tx_fifo_0/mitx_petalinux_i2s_tx_fifo_0/mitx_petalinux_i2s_tx_fifo_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mitx_petalinux_i2s_tx_fifo_0 || ORIG_REF_NAME==mitx_petalinux_i2s_tx_fifo_0}] {/inst }]/inst ]]

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_converter_0_0/constraints/converter_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_saw_1_0/constraints/saw_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_saw_2_0/constraints/saw_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_saw_3_0/constraints/saw_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_mixer_0_0/constraints/mixer_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_latcherfloat_0_1/constraints/latcherfloat_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_saw_4_0/constraints/saw_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_latcherfloat_1_0/constraints/latcherfloat_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_FM_Synth_0_0/constraints/FM_Synth_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_xbar_0/mitx_petalinux_xbar_0_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_xbar_1/mitx_petalinux_xbar_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_xbar_2/mitx_petalinux_xbar_2_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_9/mitx_petalinux_auto_pc_9_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_8/mitx_petalinux_auto_pc_8_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_7/mitx_petalinux_auto_pc_7_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_11/mitx_petalinux_auto_pc_11_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_10/mitx_petalinux_auto_pc_10_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_ss_slidr_0/mitx_petalinux_auto_ss_slidr_0_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_ss_slid_1/mitx_petalinux_auto_ss_slid_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_ss_slid_0/mitx_petalinux_auto_ss_slid_0_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_6/mitx_petalinux_auto_pc_6_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_5/mitx_petalinux_auto_pc_5_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_4/mitx_petalinux_auto_pc_4_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_3/mitx_petalinux_auto_pc_3_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_2/mitx_petalinux_auto_pc_2_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_1/mitx_petalinux_auto_pc_1_ooc.xdc

# XDC: bd/mitx_petalinux/ip/mitx_petalinux_auto_pc_0/mitx_petalinux_auto_pc_0_ooc.xdc

# XDC: bd/mitx_petalinux/mitx_petalinux_ooc.xdc
